sonar.projectName=Orbis Khata Boi
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src,e2e
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**,e2e/**/*.spec.ts
sonar.coverage.exclusions=src/main.tsx,src/vite-env.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.cpd.exclusions=src/**/copy.ts
