import type { Language } from '../i18n'
const en = {
  company: 'Company', newCompany: 'New company', companyName: 'Company name', create: 'Create',
  title: 'Your business, in balance.', subtitle: 'Live books · INR · India time',
  cash: 'Cash', bank: 'Bank / UPI', receivable: 'Customer dues', payable: 'Supplier dues', sales: 'Sales', purchases: 'Purchases',
  advanceCustomer: 'Customer advances', advanceSupplier: 'Supplier advances', closing: 'Closing balance', period: 'Selected period',
  sale: 'Sale', purchase: 'Purchase', receipt: 'Receive money', payment: 'Pay money', reversal: 'Reversal',
  parties: 'Customers & suppliers', newParty: 'Add party', partyName: 'Party name', customer: 'Customer', supplier: 'Supplier', both: 'Both',
  kind: 'Type', party: 'Party', all: 'All parties', amount: 'Amount (INR)', date: 'Date', method: 'Paid into / from',
  reference: 'Bill / reference', note: 'Note / reversal reason', review: 'Review entry', confirm: 'Confirm & save', edit: 'Edit', cancel: 'Cancel',
  reviewHint: 'Check company, party and amount. Posted entries cannot be edited; mistakes are corrected with a reversal.',
  invoiceHint: 'A sale or purchase records the bill, not money. Record each receipt or payment separately.',
  loading: 'Loading your books…', error: 'Could not load the books. Check your connection and retry.', retry: 'Retry', saved: 'Saved successfully.',
  pending: 'Save not yet confirmed. Retry this same entry; do not enter it again. It will not post twice.',
  validation: 'Enter a valid positive amount with at most 2 decimal places.', storage: 'Browser storage is unavailable. Enable it before posting so interrupted saves can be recovered.',
  ledger: 'Party ledger & activity', empty: 'No entries for this period. Add a party, record a bill, then record money received or paid.',
  from: 'From', to: 'To', refresh: 'Refresh', opening: 'Opening balance', dr: 'Debit', cr: 'Credit', reverse: 'Reverse', reversed: 'Reversed',
  previous: 'Previous', next: 'Next', entries: 'entries', separate: 'Only this company’s books. Other companies stay separate.',
  noParties: 'Add a customer or supplier to start.', posted: 'Posted', trial: 'Journal balanced', cashWarning: 'Negative cash balance: check missing receipts or earlier entries.',
  scope: 'Basic double-entry books. GST, inventory, opening-balance import and offline backup are not enabled yet.',
  saving: 'Saving…', locked: 'Finish the pending save before switching companies.', range: 'Choose a valid date range.',
  rejected: 'This entry was rejected and not saved. Review the details or cancel, refresh and try again.',
}
type Copy = typeof en
const bn: Copy = {
  company: 'কোম্পানি', newCompany: 'নতুন কোম্পানি', companyName: 'কোম্পানির নাম', create: 'তৈরি করুন',
  title: 'আপনার ব্যবসা, পরিষ্কার হিসাব।', subtitle: 'বাস্তব হিসাব · INR · ভারতীয় সময়',
  cash: 'ক্যাশ', bank: 'ব্যাংক / UPI', receivable: 'কাস্টমারের কাছে পাওনা', payable: 'সাপ্লায়ারকে দেনা', sales: 'বিক্রি', purchases: 'কেনা',
  advanceCustomer: 'কাস্টমারের অগ্রিম', advanceSupplier: 'সাপ্লায়ারকে অগ্রিম', closing: 'শেষ তারিখের ব্যালেন্স', period: 'নির্বাচিত সময়ের হিসাব',
  sale: 'বিক্রি', purchase: 'কেনা', receipt: 'টাকা গ্রহণ', payment: 'পেমেন্ট', reversal: 'উল্টো এন্ট্রি',
  parties: 'কাস্টমার ও সাপ্লায়ার', newParty: 'নতুন পার্টি', partyName: 'পার্টির নাম', customer: 'কাস্টমার', supplier: 'সাপ্লায়ার', both: 'দুই ধরনের',
  kind: 'ধরন', party: 'পার্টি', all: 'সব পার্টি', amount: 'টাকার পরিমাণ (INR)', date: 'তারিখ', method: 'টাকা জমা / দেওয়ার মাধ্যম',
  reference: 'বিল / রেফারেন্স', note: 'নোট / উল্টো এন্ট্রির কারণ', review: 'এন্ট্রি যাচাই করুন', confirm: 'নিশ্চিত করে সেভ', edit: 'সংশোধন', cancel: 'বাতিল',
  reviewHint: 'কোম্পানি, পার্টি ও টাকা মিলিয়ে নিন। সেভ করা এন্ট্রি বদলানো যাবে না; ভুল হলে উল্টো এন্ট্রি করতে হবে।',
  invoiceHint: 'বিক্রি বা কেনায় বিলের হিসাব হবে, ক্যাশ নয়। প্রতিবার টাকা নেওয়া বা দেওয়ার আলাদা এন্ট্রি করুন।',
  loading: 'আপনার হিসাব লোড হচ্ছে…', error: 'হিসাব লোড হয়নি। সংযোগ দেখে আবার চেষ্টা করুন।', retry: 'আবার চেষ্টা করুন', saved: 'সফলভাবে সেভ হয়েছে।',
  pending: 'সেভ নিশ্চিত হয়নি। এই একই এন্ট্রি আবার চেষ্টা করুন; নতুন করে দেবেন না। একই এন্ট্রি দুবার জমা হবে না।',
  validation: 'শূন্যের বেশি টাকা লিখুন; দশমিকের পরে সর্বোচ্চ ২ ঘর।', storage: 'ব্রাউজারের স্টোরেজ চালু করুন, যাতে সেভের মাঝখানে বন্ধ হলেও এন্ট্রি উদ্ধার হয়।',
  ledger: 'পার্টির লেজার ও লেনদেন', empty: 'এই সময়ে কোনো এন্ট্রি নেই। পার্টি তৈরি করে বিল ও টাকা নেওয়া-দেওয়া আলাদা লিখুন।',
  from: 'শুরুর তারিখ', to: 'শেষ তারিখ', refresh: 'রিফ্রেশ', opening: 'শুরুর ব্যালেন্স', dr: 'ডেবিট', cr: 'ক্রেডিট', reverse: 'উল্টো এন্ট্রি', reversed: 'উল্টো এন্ট্রি হয়েছে',
  previous: 'আগের', next: 'পরের', entries: 'এন্ট্রি', separate: 'শুধু এই কোম্পানির হিসাব। অন্য কোম্পানির হিসাব সম্পূর্ণ আলাদা।',
  noParties: 'হিসাব শুরু করতে কাস্টমার বা সাপ্লায়ার তৈরি করুন।', posted: 'সেভ হয়েছে', trial: 'জার্নাল মিলেছে', cashWarning: 'ক্যাশ মাইনাস: বাদ পড়া টাকা গ্রহণ বা আগের হিসাব পরীক্ষা করুন।',
  scope: 'বেসিক ডাবল-এন্ট্রি হিসাব। GST, স্টক, শুরুর ব্যালেন্স আমদানি ও অফলাইন ব্যাকআপ এখনও চালু নয়।',
  saving: 'সেভ হচ্ছে…', locked: 'কোম্পানি বদলানোর আগে অসম্পূর্ণ সেভ শেষ করুন।', range: 'সঠিক তারিখের সীমা দিন।',
  rejected: 'এই এন্ট্রি গ্রহণ করা হয়নি, সেভ হয়নি। তথ্য সংশোধন করুন অথবা বাতিল করে রিফ্রেশ করুন।',
}
const hi: Copy = {
  ...en,
  company: 'कंपनी', newCompany: 'नई कंपनी', companyName: 'कंपनी का नाम', create: 'बनाएँ', title: 'आपका व्यवसाय, साफ़ हिसाब।', subtitle: 'वास्तविक हिसाब · INR · भारतीय समय',
  cash: 'नकद', bank: 'बैंक / UPI', receivable: 'ग्राहक से लेना', payable: 'सप्लायर को देना', sales: 'बिक्री', purchases: 'खरीद',
  advanceCustomer: 'ग्राहक का अग्रिम', advanceSupplier: 'सप्लायर को अग्रिम', closing: 'अंतिम शेष', period: 'चुनी हुई अवधि',
  sale: 'बिक्री', purchase: 'खरीद', receipt: 'पैसे लें', payment: 'भुगतान', reversal: 'उल्टी प्रविष्टि', parties: 'ग्राहक व सप्लायर', newParty: 'पार्टी जोड़ें', partyName: 'पार्टी का नाम', customer: 'ग्राहक', supplier: 'सप्लायर', both: 'दोनों',
  kind: 'प्रकार', party: 'पार्टी', all: 'सभी पार्टियाँ', amount: 'राशि (INR)', date: 'तारीख', method: 'नकद या बैंक', reference: 'बिल / संदर्भ', note: 'नोट / उल्टी प्रविष्टि का कारण', review: 'जाँचें', confirm: 'पुष्टि और सेव', edit: 'बदलें', cancel: 'रद्द करें',
  reviewHint: 'कंपनी, पार्टी और राशि जाँचें। सेव की हुई प्रविष्टि बदली नहीं जाएगी; सुधार के लिए उल्टी प्रविष्टि करें।', invoiceHint: 'बिक्री और खरीद बिल हैं, नकद नहीं। हर भुगतान अलग दर्ज करें।',
  loading: 'हिसाब लोड हो रहा है…', error: 'हिसाब लोड नहीं हुआ। कनेक्शन जाँचकर फिर कोशिश करें।', retry: 'फिर कोशिश करें', saved: 'सेव हो गया।', pending: 'सेव की पुष्टि नहीं हुई। इसी प्रविष्टि को फिर भेजें; नई न बनाएँ। दोहरी पोस्टिंग नहीं होगी।',
  validation: 'शून्य से अधिक राशि, अधिकतम दो दशमलव अंक लिखें।', storage: 'ब्राउज़र स्टोरेज चालू करें ताकि अधूरी सेव पुनः भेज सकें।', ledger: 'पार्टी लेजर और गतिविधि', empty: 'इस अवधि में कोई प्रविष्टि नहीं। पहले पार्टी, फिर बिल और भुगतान दर्ज करें।',
  from: 'से', to: 'तक', refresh: 'रिफ्रेश', opening: 'प्रारंभिक शेष', dr: 'डेबिट', cr: 'क्रेडिट', reverse: 'उल्टी प्रविष्टि', reversed: 'उल्टी प्रविष्टि हो गई', previous: 'पिछला', next: 'अगला', entries: 'प्रविष्टियाँ', separate: 'केवल इस कंपनी का हिसाब। अन्य कंपनियाँ अलग हैं।',
  noParties: 'पहले ग्राहक या सप्लायर जोड़ें।', posted: 'सेव हुआ', trial: 'जर्नल संतुलित', cashWarning: 'नकद ऋणात्मक है: छूटी हुई रसीदें या पुराने हिसाब जाँचें।', scope: 'बुनियादी डबल-एंट्री हिसाब। GST, स्टॉक, शुरुआती शेष आयात और ऑफलाइन बैकअप अभी उपलब्ध नहीं हैं।', saving: 'सेव हो रहा है…', locked: 'कंपनी बदलने से पहले अधूरी सेव पूरी करें।', range: 'सही तारीख सीमा चुनें।',
}
export const accountingCopy: Record<Language, Copy> = { en, bn, hi }
